[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"

size = 11

# Everforest theme colors
[colors.primary]
background = '#0d0d0d'
foreground = '#d3c6aa'

[colors.normal]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

[colors.bright]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

[colors.selection]
background = '#503946'
text = '#d3c6aa'

# Tmux window switching with Cmd+number
[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u001b1"

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u001b2"

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\u001b3"

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u001b4"

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u001b5"

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u001b6"

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u001b7"

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u001b8"

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u001b9"
