[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8

decorations = "Buttonless"

opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"

size = 11

# Tokyo Night theme colors
[colors.primary]
background = '#0d0d0d'
foreground = '#c0caf5'

[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

[colors.selection]
background = '#33467c'
text = '#c0caf5'

# Tmux window switching with Cmd+number
[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u001b1"

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u001b2"

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\u001b3"

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u001b4"

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u001b5"

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u001b6"

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u001b7"

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u001b8"

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u001b9"
